config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :beers do
    end
  end

  resources :beer_table, only: %i[] do
    get :search, on: :collection
  end

  get 'contact', to: 'static/contents#contact_us'
  get 'gallery', to: 'static/contents#gallery'
  get 'beer_table', to: 'beer_table#beer_table'

  root 'beer_table#beer_table'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/beers_controller.rb
module Admin
  class BeersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_beer, only: %i[show edit update destroy]

    def index
      @beers = Beer.all.order(opened: :desc)
    end

    def show; end

    def new
      @beer = Beer.new
    end

    def edit; end

    def create
      @beer = Beer.new(beer_params)

      respond_to do |format|
        if @beer.save
          format.html { redirect_to admin_beers_path, notice: 'Beer was successfully created.' }
          format.json { render :show, status: :created, location: @beer }
        else
          format.html { render :new }
          format.json { render json: @beer.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @beer.update(beer_params)
          format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
          format.json { render :show, status: :ok, location: @beer }
        else
          format.html { render :edit }
          format.json { render json: @beer.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @beer.destroy
      respond_to do |format|
        format.html { redirect_to admin_beers_url, notice: 'Beer was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_beer
      @beer = Beer.find(params[:id])
    end

    def beer_params
      params.require(:beer).permit(:title, :description, :price, :opened)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/beer_table_controller.rb
class BeerTableController < ApplicationController
  Search = Struct.new(:query)

  def beer_table; end

  def search
    render json: all_beers
  end

  private

  def all_beers
    beers = Beer.order(opened: :desc)

    search = Search.new(params[:query])
    add_filters(beers, search)
  end

  def add_filters(beers, search)
    beers = add_query_filter(beers, search.query)
    beers
  end

  def add_query_filter(beers, query)
    return beers if query.empty?

    beers.where('title ILIKE :q OR description ILIKE :q', q: "%#{query}%")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beer_table_helper.rb
module BeerTableHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/admin/beers/_form.html.erb
<%= form_with(model: beer, url: admin_beers_path) do |form| %>
  <% if beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :beer_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :beer_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :beer_price %>
  </div>

  <div class="field">
    <%= form.label :opened %>
    <%= form.datetime_select :opened, id: :beer_opened %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form', beer: @beer %>

<%= link_to 'Show', admin_beer_path(@beer) %> |
<%= link_to 'Back', admin_beers_path %>

app/views/admin/beers/index.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.0.0/js/all.js"></script>
</head>







<section class="hero">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title is-centered">
        Beers
      </h1>
      <h2 class="subtitle">
        Some generic shiet
      </h2>
    </div>
  </div>
</section>




<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Price</th>
    <th>Opened</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @beers.each do |beer| %>
    <tr>
      <td><%= beer.title %></td>
      <td><%= beer.description %></td>
      <td><%= beer.price %></td>
      <td><%= beer.opened %></td>

      <% if current_user &&  current_user.admin?%>
        <td><%= link_to 'Show', admin_beer_path(beer) %></td>
        <td><%= link_to 'Edit', edit_admin_beer_path(beer) %></td>
        <td><%= link_to 'Destroy', admin_beer_path(beer), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>

    </tr>
  <% end %>
  </tbody>
</table>



<%= link_to 'New Beer', new_admin_beer_path %>


<section class="hero is-light">
  <div class="hero-body">
    <div class="columns">
      <div class="column">
        <div class="content has-text-centered">
          <p>Deeply inspired by my brother, that happens to be a professional code magician. Check out his page and give him some love: <a href="https://shovik.com/"><strong>shovik.com</strong></a> </p>
        </div>
      </div>
      <div class="column has-text-centered i">
        <p>Contact me:</p>
        <a href="https://vk.com/hz_kto_eto"><i class="fab fa-vk fa-2x has-text-dark" aria-hidden="true"></i></a>
        <a href="https://www.facebook.com/jaroslav.kovshovik"> <i class="fab fa-facebook-f fa-2x has-text-dark" aria-hidden="true"></i></a>
        <a href="https://github.com/Bylbanos"><i class="fab fa-github-alt fa-2x has-text-dark" aria-hidden="true"></i></a>
        <a href="https://www.instagram.com/bylbanos/?hl=ru"><i class="fas fa-camera fa-2x has-text-dark" aria-hidden="true"></i></a>
      </div>
      <div class="column has-text-centered">
        <p><s>Proudly</s></p>
        <a href="https://bulma.io">
          <img src="https://bulma.io/images/made-with-bulma.png" alt="Made with Bulma" width="256" height="48">
        </a>
      </div>
    </div>
  </div>
</section>

app/views/admin/beers/new.html.erb
<h1>New Beer</h1>

<%= render 'form', beer: @beer %>

<%= link_to 'Back', admin_beers_path %>

app/views/admin/beers/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @beer.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @beer.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @beer.price %>
</p>

<p>
  <strong>Opened:</strong>
  <%= @beer.opened %>
</p>

<%= link_to 'Edit', edit_admin_beer_path(@beer) %> |
<%= link_to 'Back', admin_beers_path %>

app/views/beer_table/beer_table.html.erb
<head>
  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
</head>

<body>
  <div class="section">
    <%= react_component('Index') %>
    <%= render partial: 'layouts/edit_beers' %>
  </div>`
</body>

app/views/beers/_form.html.erb
<%= form_with(model: beer, local: true) do |form| %>
  <% if beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :beer_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :beer_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :beer_price %>
  </div>

  <div class="field">
    <%= form.label :opened %>
    <%= form.datetime_select :opened, id: :beer_opened %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/beers/beer_table.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hello Bulma!</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.0.0/js/all.js"></script>

</head>




<div class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-offset-3 is-2 has-text-centered">
        <%= link_to "Beer", root_path, class: "button is-active is-dark is-medium is-fullwidth is-outlined" %>
      </div>
      <div class="column is-2 has-text-centered">
        <%= link_to "Gallery", gallery_path, class: "button is-dark is-medium is-fullwidth is-outlined" %>
      </div>
      <div class="column is-2 has-text-centered">
        <%= link_to "Contact Us", contact_path, class: "button is-dark is-medium is-fullwidth is-outlined" %>
      </div>
    </div>
  </div>
</div>


<%= react_component('Index') %>

<% if current_user &&  current_user.admin?%>
  <%= link_to 'Edit beers', beers_path %>
<% end %>

app/views/beers/contact_us.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hello Bulma!</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.0.0/js/all.js"></script>
</head>


<div class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-offset-3 is-2 has-text-centered">
        <%= link_to "Beer", root_path, class: "button is-active is-dark is-medium is-fullwidth is-outlined" %>
      </div>
      <div class="column is-2 has-text-centered">
        <%= link_to "Gallery", gallery_path, class: "button is-dark is-medium is-fullwidth is-outlined" %>
      </div>
      <div class="column is-2 has-text-centered">
        <%= link_to "Contact Us", contact_path, class: "button is-dark is-medium is-fullwidth is-outlined" %>
      </div>
    </div>
  </div>
</div>
<h1>Contact us bliat'</h1>

app/views/beers/gallery.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hello Bulma!</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.0.0/js/all.js"></script>

</head>




<div class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-offset-3 is-2 has-text-centered">
        <%= link_to "Beer", root_path, class: "button is-active is-dark is-medium is-fullwidth is-outlined" %>
      </div>
      <div class="column is-2 has-text-centered">
        <%= link_to "Gallery", gallery_path, class: "button is-dark is-medium is-fullwidth is-outlined" %>
      </div>
      <div class="column is-2 has-text-centered">
        <%= link_to "Contact Us", contact_path, class: "button is-dark is-medium is-fullwidth is-outlined" %>
      </div>
    </div>
  </div>
</div>

<% if current_user &&  current_user.admin?%>
  <%= link_to 'Edit beers', beers_path %>
<% end %>

app/views/beers/index.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hello Bulma!</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.0.0/js/all.js"></script>
</head>



<div class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-offset-3 is-2 has-text-centered">
        <%= link_to "Beer", root_path, class: "button is-active is-dark is-medium is-fullwidth is-outlined" %>
      </div>
      <div class="column is-2 has-text-centered">
        <%= link_to "Gallery", gallery_path, class: "button is-dark is-medium is-fullwidth is-outlined" %>
      </div>
      <div class="column is-2 has-text-centered">
        <%= link_to "Contact Us", contact_path, class: "button is-dark is-medium is-fullwidth is-outlined" %>
      </div>
    </div>
  </div>
</div>




<section class="hero">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title is-centered">
        Beers
      </h1>
      <h2 class="subtitle">
        Some generic shiet
      </h2>
    </div>
  </div>
</section>




<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Price</th>
    <th>Opened</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @beers.each do |beer| %>
    <tr>
      <td><%= beer.title %></td>
      <td><%= beer.description %></td>
      <td><%= beer.price %></td>
      <td><%= beer.opened %></td>

      <% if current_user &&  current_user.admin?%>
        <td><%= link_to 'Show', beer %></td>
        <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
        <td><%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>

    </tr>
  <% end %>
  </tbody>
</table>



<%= link_to 'New Beer', new_beer_path %>


<section class="hero is-light">
  <div class="hero-body">
    <div class="columns">
      <div class="column">
        <div class="content has-text-centered">
          <p>Deeply inspired by my brother, that happens to be a professional code magician. Check out his page and give him some love: <a href="https://shovik.com/"><strong>shovik.com</strong></a> </p>
        </div>
      </div>
      <div class="column has-text-centered i">
        <p>Contact me:</p>
        <a href="https://vk.com/hz_kto_eto"><i class="fab fa-vk fa-2x has-text-dark" aria-hidden="true"></i></a>
        <a href="https://www.facebook.com/jaroslav.kovshovik"> <i class="fab fa-facebook-f fa-2x has-text-dark" aria-hidden="true"></i></a>
        <a href="https://github.com/Bylbanos"><i class="fab fa-github-alt fa-2x has-text-dark" aria-hidden="true"></i></a>
        <a href="https://www.instagram.com/bylbanos/?hl=ru"><i class="fas fa-camera fa-2x has-text-dark" aria-hidden="true"></i></a>

      </div>
      <div class="column has-text-centered">
        <p><s>Proudly</s></p>
        <a href="https://bulma.io">
          <img src="https://bulma.io/images/made-with-bulma.png" alt="Made with Bulma" width="256" height="48">
        </a>
      </div>
    </div>
  </div>
</section>

app/views/beers/new.html.erb
<h1>New Beer</h1>

<%= render 'form', beer: @beer %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @beer.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @beer.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @beer.price %>
</p>

<p>
  <strong>Opened:</strong>
  <%= @beer.opened %>
</p>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>

app/views/layouts/_edit_beers.html.erb
<% if current_user &&  current_user.admin?%>
<div class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-offset-5 is-2 has-text-centered">
        <%= link_to 'Edit beers', admin_beers_path, class: 'button is-dark is-medium is-fullwidth is-outlined' %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="columns">
      <div class="column">
        <div class="content has-text-centered">
          <p>Deeply inspired by my brother, that happens to be a professional code magician. Check out his page and give him some love: <a href="https://shovik.com/"><strong>shovik.com</strong></a> </p>
        </div>
      </div>
      <div class="column has-text-centered i">
        <p>Contact me:</p>
        <a href="https://vk.com/hz_kto_eto"><i class="fab fa-vk fa-2x has-text-dark" aria-hidden="true"></i></a>
        <a href="https://www.facebook.com/jaroslav.kovshovik"> <i class="fab fa-facebook-f fa-2x has-text-dark" aria-hidden="true"></i></a>
        <a href="https://github.com/Bylbanos"><i class="fab fa-github-alt fa-2x has-text-dark" aria-hidden="true"></i></a>
        <a href="https://www.instagram.com/bylbanos/?hl=ru"><i class="fas fa-camera fa-2x has-text-dark" aria-hidden="true"></i></a>
        <br>
        <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'button is-dark is-small is-outlined'  %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: 'button is-dark is-small is-outlined'  %>
        <% end %>
      </div>
      <div class="column has-text-centered">
        <p><s>Proudly</s></p>
        <a href="https://bulma.io">
          <img src="https://bulma.io/images/made-with-bulma.png" alt="Made with Bulma" width="256" height="48">
        </a>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<div class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-offset-3 is-2 has-text-centered">
        <%= link_to "Beer", root_path, class: "button is-active is-dark is-medium is-fullwidth is-outlined" %>
      </div>
      <div class="column is-2 has-text-centered">
        <%= link_to "Gallery", gallery_path, class: "button is-dark is-medium is-fullwidth is-outlined" %>
      </div>
      <div class="column is-2 has-text-centered">
        <%= link_to "Contact Us", contact_path, class: "button is-dark is-medium is-fullwidth is-outlined" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oktoberfest Beer</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <% if notice %>
    <div class="notification is-success is-marginless"><button class="delete"></button><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="notification is-danger is-marginless"><button class="delete"><%= alert %></button></div>
    <% end %>

    <%= render partial: 'layouts/navbar' %>

    <%= yield %>

    <%= render partial: 'layouts/footer' %>
  </body>
</html>